name: lynx-catbot

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../dockerfile.backend
    image: lynx-catbot-backend:latest
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./backend:/app
      - backend_static:/app/static
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: ../dockerfile.frontend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  frontend_node_modules: {}
  backend_static: {}
