FROM node:20-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
  python3 \
  make \
  g++ \
  && rm -rf /var/lib/apt/lists/*

RUN npm cache clean --force

COPY package.json package-lock.json ./

RUN ls -la /app

RUN npm ci

RUN npm rebuild

COPY . ./

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]