# Generated by Django 4.2.19 on 2025-03-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_fixedcontent_options_alter_fixedcontent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedcontent',
            name='category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fixedcontent',
            name='subcategory',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fixedcontent',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fixedcontent',
            name='answer',
            field=models.TextField(),
        )

    ]
