# Generated by Django 4.2.19 on 2025-03-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250304_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedcontent',
            name='answer',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='fixedcontent',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fixedcontent',
            name='question',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fixedcontent',
            name='subcategory',
            field=models.CharField(max_length=50),
        ),
    ]
